### ISSUE TITLE
Double Clicking the Program Counter crashes emulated CPU while paused at a memory write breakpoint

### ISSUE THREAD

**Issue by ghost** [slajerek/RetroDebugger#18]
**Describe the bug**
Double clicking the PC set it to 0000 and crashes the application (unable to reset).

**To Reproduce**
Double Click on the Program Counter while a c64 program is executing and is paused at a memory write break point.

**Expected behavior**
I assumed this would take me to the execution address in the monitor window.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by slajerek** [comment]
@RoyBatty64 No, changing PC sets the emulator's current PC to selected value, if you set it to 0000 then emulator's CPU crashed as there's garbage code there. I assume that emulation is paused after CPU jam, that's why reset does not work, you need to unpause emulation. I've added option to always unpause emulation on reset. Please confirm.

To go to address in Disassembly view you need to press Ctrl+G in Disassembly view.
